name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - name: Maven Package
        run: make test
