# This is a basic workflow to help you get started with Actions
name: Master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Unit Test
    steps:
      - name: Maven Package
        run: make test
